 # Config for training ALAE on beau at resolution 512x512

NAME: beau
DATASET:
  PART_COUNT: 8
  SIZE: 29009
  FFHQ_SOURCE: /media/hermes/dataspace/fl/dataset_tf/b/b_%02d.tfrecords
  PATH: /media/hermes/dataspace/fl/dataset_tf/b_split/b_%02d.tfrecords.%03d

  PART_COUNT_TEST: 1
  PATH_TEST: /media/hermes/dataspace/fl/dataset_tf/b_split_test/b_%02d.tfrecords.%03d

  SAMPLES_PATH: dataset_samples/faces/realign512x512
  STYLE_MIX_PATH: style_mixing/test_images/set_beau

  MAX_RESOLUTION_LEVEL: 9

MODEL:
  LATENT_SPACE_SIZE: 512
  LAYER_COUNT: 8
  MAX_CHANNEL_COUNT: 512
  START_CHANNEL_COUNT: 32
  DLATENT_AVG_BETA: 0.995
  MAPPING_LAYERS: 8

OUTPUT_DIR: training_artifacts/beau

TRAIN:
  BASE_LEARNING_RATE: 0.002
  EPOCHS_PER_LOD: 16
  LEARNING_DECAY_RATE: 0.1
  LEARNING_DECAY_STEPS: []
  TRAIN_EPOCHS: 300
  #                    4    8   16    32    64    128    256
  LOD_2_BATCH_8GPU: [512, 256, 128,   64,   32,    32,    32,       32,        32] # If GPU memory ~16GB reduce last number from 32 to 24
  LOD_2_BATCH_4GPU: [512, 256, 128,   64,   32,    32,    32,       16]
  LOD_2_BATCH_2GPU: [512, 256, 128,   64,   32,    32,    16]
  LOD_2_BATCH_1GPU: [512, 256, 128,   64,   32,    16]

  LEARNING_RATES: [0.0015,  0.0015,   0.0015,   0.0015,  0.0015,   0.0015,     0.002,     0.003,    0.003]
